/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package vn.edu.hcmut.tachometer.core;

public class tachometer_process {
  public static SWIGTYPE_p_void Tachometer_Create() {
    long cPtr = tachometer_processJNI.Tachometer_Create();
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static long Tachometer_Init(SWIGTYPE_p_void tacho) {
    return tachometer_processJNI.Tachometer_Init(SWIGTYPE_p_void.getCPtr(tacho));
  }

  public static long Tachometer_Free(SWIGTYPE_p_void tacho) {
    return tachometer_processJNI.Tachometer_Free(SWIGTYPE_p_void.getCPtr(tacho));
  }

  public static long Tachometer_Config(SWIGTYPE_p_void tacho, long estimatedFreq) {
    return tachometer_processJNI.Tachometer_Config(SWIGTYPE_p_void.getCPtr(tacho), estimatedFreq);
  }

  public static long Tachometer_Process(SWIGTYPE_p_void tacho, short[] inAudio, SWIGTYPE_p_float resultFreq) {
    return tachometer_processJNI.Tachometer_Process(SWIGTYPE_p_void.getCPtr(tacho), inAudio, SWIGTYPE_p_float.getCPtr(resultFreq));
  }

}
