/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

#define TACHO_FRAME_LENGTH			1280

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>

/* Support for throwing Java exceptions */
typedef enum {
	SWIG_JavaOutOfMemoryError = 1,
	SWIG_JavaIOException,
	SWIG_JavaRuntimeException,
	SWIG_JavaIndexOutOfBoundsException,
	SWIG_JavaArithmeticException,
	SWIG_JavaIllegalArgumentException,
	SWIG_JavaNullPointerException,
	SWIG_JavaDirectorPureVirtual,
	SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
	SWIG_JavaExceptionCodes code;
	const char *java_exception;
} SWIG_JavaExceptions_t;

static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv,
		SWIG_JavaExceptionCodes code, const char *msg) {
	jclass excep;
	static const SWIG_JavaExceptions_t java_exceptions[] = { {
			SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" }, {
			SWIG_JavaIOException, "java/io/IOException" }, {
			SWIG_JavaRuntimeException, "java/lang/RuntimeException" }, {
			SWIG_JavaIndexOutOfBoundsException,
			"java/lang/IndexOutOfBoundsException" }, {
			SWIG_JavaArithmeticException, "java/lang/ArithmeticException" }, {
			SWIG_JavaIllegalArgumentException,
			"java/lang/IllegalArgumentException" }, {
			SWIG_JavaNullPointerException, "java/lang/NullPointerException" }, {
			SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" }, {
			SWIG_JavaUnknownError, "java/lang/UnknownError" }, {
			(SWIG_JavaExceptionCodes) 0, "java/lang/UnknownError" } };
	const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

	while (except_ptr->code != code && except_ptr->code)
		except_ptr++;

	(*jenv)->ExceptionClear(jenv);
	excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
	if (excep)
		(*jenv)->ThrowNew(jenv, excep, msg);
}

/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else

extern void* Tachometer_Create();
extern int32_t Tachometer_Init(void* tacho);
extern int32_t Tachometer_Free(void* tacho);
extern int32_t Tachometer_Config(void* tacho, int32_t estimatedFreq);
extern int32_t Tachometer_Get_Audio_Frame_Location(void* tacho,
		int16_t** audioFrame);
extern int32_t Tachometer_Push(void* tacho, int16_t* inAudio, int32_t size);
extern float Tachometer_Process(void* tacho);
extern float Tachometer_FFT_Out(void* tacho, int32_t beginFreq,
		int32_t endFreq, int32_t size, float* fft_out_magnitude);

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_vn_edu_hcmut_tachometer_core_tachometer_1processJNI_Tachometer_1Create(
		JNIEnv *jenv, jclass jcls) {
	jlong jresult = 0;
	void *result = 0;

	(void) jenv;
	(void) jcls;
	result = (void *) Tachometer_Create();
	*(void **) &jresult = result;
	return jresult;
}

SWIGEXPORT jlong JNICALL Java_vn_edu_hcmut_tachometer_core_tachometer_1processJNI_Tachometer_1Init(
		JNIEnv *jenv, jclass jcls, jlong jarg1) {
	jlong jresult = 0;
	void *arg1 = (void *) 0;
	int32_t result;

	(void) jenv;
	(void) jcls;
	arg1 = *(void **) &jarg1;
	result = Tachometer_Init(arg1);
	jresult = result;
	return jresult;
}

SWIGEXPORT jlong JNICALL Java_vn_edu_hcmut_tachometer_core_tachometer_1processJNI_Tachometer_1Free(
		JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jbyteBuffer) {
	jlong jresult = 0;
	void *arg1 = (void *) 0;
	int32_t result;

	(void) jenv;
	(void) jcls;
	arg1 = *(void **) &jarg1;
	result = Tachometer_Free(arg1);
//	(*jenv)->DeleteGlobalRef(jenv, jbyteBuffer);
	jresult = result;
	return jresult;
}

SWIGEXPORT jlong JNICALL Java_vn_edu_hcmut_tachometer_core_tachometer_1processJNI_Tachometer_1Config(
		JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
	jlong jresult = 0;
	void *arg1 = (void *) 0;
	int32_t arg2;
	int32_t argp2;
	int32_t result;

	(void) jenv;
	(void) jcls;
	arg1 = *(void **) &jarg1;
	argp2 = *(int32_t *) &jarg2;
	arg2 = argp2;
	result = Tachometer_Config(arg1, arg2);
	jresult = result;
	return jresult;
}

SWIGEXPORT jobject JNICALL Java_vn_edu_hcmut_tachometer_core_tachometer_1processJNI_Tachometer_1Get_1Audio_1Frame_1Location(
		JNIEnv *jenv, jclass jcls, jlong jtacho) {
	(void) jenv;
	(void) jcls;
	void *tacho = *(void **) &jtacho;
	int16_t* audioFrame;
	int32_t ret = Tachometer_Get_Audio_Frame_Location(tacho, &audioFrame);
	if (ret != 0) {
		return NULL;
	} else {
		jobject directBuffer = (*jenv)->NewDirectByteBuffer(jenv,
				(void*) audioFrame, TACHO_FRAME_LENGTH << 1);
		jobject globalRef = (*jenv)->NewGlobalRef(jenv, directBuffer);
		return globalRef;
	}
}

SWIGEXPORT jlong JNICALL Java_vn_edu_hcmut_tachometer_core_tachometer_1processJNI_Tachometer_1Push(
		JNIEnv *jenv, jclass jcls, jlong jtacho, jobject jbyteBuffer,
		jlong jsize) {
	jlong jresult = 0;

	void* inAudio = (*jenv)->GetDirectBufferAddress(jenv, jbyteBuffer);
	int32_t size = *(int32_t*) &jsize;
	void* tacho = *(void**) &jtacho;
	int32_t ret = Tachometer_Push(tacho, (int16_t*) inAudio, (size >> 1));

	jresult = (jlong) ret;
	return jresult;
}

SWIGEXPORT jfloat JNICALL Java_vn_edu_hcmut_tachometer_core_tachometer_1processJNI_Tachometer_1Process(
		JNIEnv *jenv, jclass jcls, jlong jtacho) {
	(void) jenv;
	(void) jcls;
	int32_t* tacho = *(void **) &jtacho;
	float result = Tachometer_Process(tacho);
	return (jfloat) result;
}

SWIGEXPORT jfloat JNICALL Java_vn_edu_hcmut_tachometer_core_tachometer_1processJNI_Tachometer_1FFT_1Out(
		JNIEnv *jenv, jclass jcls, jlong jtacho, jint jbeginFreq, jint jendFreq,
		jint jsize, jfloatArray jfft_out_magnitude) {
	(void) jenv;
	(void) jcls;
	int32_t beginFreq = (int32_t) jbeginFreq;
	int32_t endFreq = (int32_t) jendFreq;
	int32_t size = (int32_t) jsize;
	void *tacho = *(void **) &jtacho;
	jfloat* jtmp_fft_out_magnitude = (*jenv)->GetFloatArrayElements(jenv,
			jfft_out_magnitude, 0);

	float* fft_out_magnitude = *(float**) &jtmp_fft_out_magnitude;
	float result = Tachometer_FFT_Out(tacho, beginFreq, endFreq, size,
			fft_out_magnitude);

	(*jenv)->ReleaseFloatArrayElements(jenv, jfft_out_magnitude,
			jtmp_fft_out_magnitude, 0); // Copy back and release the memory

	return (jfloat)result;
}

#ifdef __cplusplus
}
#endif

